name: Workflow for Codecov example-c
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile BBSK_Psycho
        run: gcc -fprofile-arcs -ftest-coverage -O0 -o BBSK-Psychologists.Tests BBSK-Psychologists.Tests BBSK_Psycho.sln
      - name: Run tests
        run: ./BBSK-Psychologists.Tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_include: BBSK_Psycho.sln
